# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Converts Time series to Complex Networks
#'
#' This function converts time domain to network domain
#' @param t Time series vector.
#' @return Returns adjacency matrix of the time series.
#' @note This procedure returns diagonal elements of adjacency matrix as connected (1).
#' @export
#' @examples
#' fahrenheit_to_kelvin(32)


VGA <- function(t) {
    .Call(`_NVG_VGA`, t)
}

main <- function() {
    .Call(`_NVG_main`)
}

vvga <- function(v) {
    .Call(`_NVG_vvga`, v)
}

