# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VGA <- function(t) {
    .Call(`_NVG_VGA`, t)
}

local_approx <- function(data, start_p, m, neighbors) {
    .Call(`_NVG_local_approx`, data, start_p, m, neighbors)
}

phase_space <- function(x, m, tau) {
    .Call(`_NVG_phase_space`, x, m, tau)
}

vvga <- function(v) {
    .Call(`_NVG_vvga`, v)
}

