# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Converts Time series to Complex Networks
#'
#' This function converts time domain to network domain
#' @param t Time series vector.
#' @return Returns adjacency matrix of the time series.
#' @note This procedure returns diagonal elements of adjacency matrix as connected (1).
#' @export
#' @examples
#' VGA(sample(10))

VGA <- function(t) {
    .Call(`_NVG_VGA`, t)
}

#' Converts multivariate Time series data in to Complex Networks
#'
#' This function takes multiple variables and convert into complex network
#' @param v multivariate time series vector.
#' @return Returns adjacency matrix of the time series.
#' @note This procedure returns diagonal elements of adjacency matrix as connected (1).
#' @note When the evaluation function is equal, a connection is establishes in the matrix (not in accordance with Lacasa et al., 2009)
#' @references Lacasa., Sivakumar, B (2009). XXX JOH, V(3),1.
#' @export
#' @examples
#' VGA(sample(10))


vvga <- function(v) {
    .Call(`_NVG_vvga`, v)
}

